// Définition des champs cibles pour chaque type d'import
// Utilisé par les hooks d'import ET les composants de mapping
import type { ChampCible } from '../types/import'

export const CHAMPS_BANCAIRES: ChampCible[] = [
  {
    cle: 'id_operation',
    label: 'N° Opération (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: false,
    aliases: [
      'n operation', 'no operation', 'numero operation', 'numerodoperation',
      'ref operation', 'reference operation', 'id operation', 'transaction id',
      'reference', 'ref', 'numero',
    ],
  },
  {
    cle: 'date_operation',
    label: 'Date opération',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['date', 'date valeur', 'date operation', 'date ope', 'date transaction', 'valeur date'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'libelle',
    label: 'Libellé',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['libelle', 'intitule', 'description', 'motif', 'objet', 'designation', 'wording'],
  },
  {
    cle: 'detail',
    label: 'Réf. client / Communication',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['detail', 'ref client', 'reference client', 'communication', 'info complementaire'],
  },
  {
    cle: 'infos_complementaires',
    label: 'Informations complémentaires',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['infos complementaires', 'informations complementaires', 'info', 'note', 'remarque', 'observation'],
    hint: 'Visible par l\'opérateur lors du lettrage',
  },
  {
    cle: 'debit',
    label: 'Débit (non-lettrable)',
    est_pivot: false,
    requis: false,
    est_lettrable: false,  // les débits ne sont pas utilisés dans le lettrage
    aliases: ['debit', 'montant debit', 'sortie', 'depense', 'retrait'],
  },
  {
    cle: 'credit',
    label: 'Crédit',
    est_pivot: false,
    requis: false,
    est_lettrable: true,
    aliases: ['credit', 'montant credit', 'entree', 'encaissement', 'versement', 'depot'],
  },
]

export const CHAMPS_LETTRAGES: ChampCible[] = [
  {
    cle: 'numero_facture',
    label: 'N° de facture (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: true,
    aliases: [
      'numero facture', 'num facture', 'no facture', 'n facture',
      'facture', 'numero de piece', 'num piece', 'no piece', 'piece', 'reference',
    ],
  },
  {
    cle: 'montant',
    label: 'Montant TTC',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['montant ttc', 'montant', 'montant lettre', 'montant paye', 'ttc', 'amount', 'total'],
    hint: 'Virgule ou point acceptés : 1 250,00 ou 1250.00',
  },
  {
    cle: 'date_lettrage',
    label: 'Date de lettrage',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['date lettrage', 'date paiement', 'date reglement', 'date', 'payment date', 'date prelevement'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'code_client',
    label: 'Code client',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'dso', 'client code'],
    hint: 'Déduit automatiquement depuis la facture si absent',
  },
  {
    cle: 'nom_client',
    label: 'Nom client',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['nom client', 'nom', 'raison sociale', 'societe', 'client'],
    hint: 'Affiché dans l\'aperçu uniquement — non stocké en base',
  },
  {
    cle: 'libelle_bancaire',
    label: 'Libellé bancaire',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['libelle bancaire', 'libelle', 'libelle virement', 'intitule', 'description virement', 'wording', 'motif virement'],
    hint: 'Optionnel — apparaît dans le Grand Livre comme libellé de l\'opération',
  },
  {
    cle: 'commentaire',
    label: 'Commentaire',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['commentaire', 'note', 'observation', 'remarque', 'info', 'precision'],
    hint: 'Optionnel — note libre visible dans l\'historique et le Grand Livre',
  },
]

export const CHAMPS_GROUPEMENTS: ChampCible[] = [
  {
    cle: 'code_client',
    label: 'Code client (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'codedso', 'dso', 'code'],
  },
  {
    cle: 'code_groupement',
    label: 'Code groupement',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['code groupement', 'codegroupement', 'groupement', 'groupe', 'group', 'code groupe'],
    hint: 'Identifiant commun à plusieurs clients du même groupe',
  },
]

export const CHAMPS_CLIENTS: ChampCible[] = [
  {
    cle: 'code_dso',
    label: 'Code client (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'codedso', 'dso', 'code', 'code_client'],
  },
  {
    cle: 'nom',
    label: 'Nom du client',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['nom', 'nom client', 'nomclient', 'raison sociale', 'raisonsociale', 'societe', 'client'],
  },
  {
    cle: 'commercial',
    label: 'Commercial',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['commercial', 'responsable commercial', 'commercial responsable', 'vendeur'],
  },
  {
    cle: 'operateur',
    label: 'Opérateur',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['operateur', 'operateur dso', 'gestionnaire', 'charge de compte'],
  },
  {
    cle: 'plateforme',
    label: "Plateforme d'envoi",
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['plateforme', 'plateforme envoi', 'portail', 'chorus', 'cegedim', 'mode envoi'],
    hint: 'Ex : Chorus, Cegedim, Tungsten…',
  },
  {
    cle: 'code_groupement',
    label: 'Code groupement',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['code groupement', 'codegroupement', 'groupement', 'groupe', 'group', 'code groupe'],
    hint: 'Identifiant commun aux clients d\'un même groupe (vue Nébuleuse)',
  },
  {
    cle: 'siret',
    label: 'SIRET',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['siret', 'n siret', 'numero siret', 'siren', 'id entreprise'],
    hint: '14 chiffres — utilisé pour la veille BODACC',
  },
]

export const CHAMPS_CONTACTS: ChampCible[] = [
  {
    cle: 'id_contact',
    label: 'ID Contact (mise à jour)',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['id contact', 'id_contact', 'identifiant contact', 'contact id', 'uuid contact'],
    hint: 'UUID généré par l\'outil — laissez vide pour un nouveau contact',
  },
  {
    cle: 'code_client',
    label: 'Code client (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'codedso', 'dso', 'code', 'code_client'],
  },
  {
    cle: 'nom',
    label: 'Nom',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['nom', 'nom contact', 'name', 'lastname', 'last name', 'nom de famille'],
  },
  {
    cle: 'prenom',
    label: 'Prénom',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['prenom', 'prénom', 'firstname', 'first name', 'prenom contact'],
  },
  {
    cle: 'email',
    label: 'Email (pivot)',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['email', 'mail', 'adresse email', 'adresse mail', 'e-mail', 'courriel'],
    hint: 'Clé de dédoublonnage — une adresse email est unique par code client',
  },
  {
    cle: 'telephone',
    label: 'Téléphone',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['telephone', 'téléphone', 'tel', 'phone', 'mobile', 'portable', 'tel direct'],
  },
  {
    cle: 'role_contact',
    label: 'Rôle',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['role', 'rôle', 'role contact', 'fonction', 'poste', 'titre'],
    hint: 'Texte libre : ex. Comptabilité, Direction, Relance…',
  },
  {
    cle: 'delete',
    label: 'Action (supprimer)',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['delete', 'action', 'supprimer', 'suppression', 'archiver'],
    hint: 'Indiquez "delete" pour désactiver ce contact',
  },
]

export const CHAMPS_FACTURES: ChampCible[] = [
  {
    cle: 'numero_piece',
    label: 'N° de pièce (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: true,
    aliases: [
      'numero piece', 'num piece', 'no piece', 'numerodepiece',
      'n facture', 'no facture', 'numero facture', 'ref facture',
      'piece', 'reference', 'ref',
    ],
  },
  {
    cle: 'code_client',
    label: 'Code client',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'codedso', 'dso', 'code'],
  },
  {
    cle: 'nom_client',
    label: 'Nom du client',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['nom client', 'nomclient', 'client', 'raison sociale', 'raisonsociale', 'nom', 'societe'],
  },
  {
    cle: 'date_emission',
    label: "Date d'émission",
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['date emission', 'datemission', 'date facture', 'datefacture', 'date creation', 'date'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'date_echeance',
    label: "Date d'échéance",
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['echeance', 'date echeance', 'dateecheance', 'due date', 'duedate', 'expiration'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'montant_ht',
    label: 'Montant HT',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['montant ht', 'montantht', 'total ht', 'totalht', 'ht', 'montant hors taxe'],
    hint: 'Virgule ou point acceptés : 1041,67 ou 1041.67',
  },
  {
    cle: 'montant_ttc',
    label: 'Montant TTC',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['montant ttc', 'montantttc', 'total ttc', 'totalttc', 'montant', 'total', 'ttc', 'amount'],
    hint: 'Virgule ou point acceptés : 1250,00 ou 1250.00',
  },
  {
    cle: 'est_avoir',
    label: 'Type document (Facture / Avoir)',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['avoir', 'est avoir', 'estavoir', 'type', 'nature document', 'type document', 'type piece'],
    hint: 'F = Facture, A = Avoir. Optionnel : auto-détecté si montant TTC négatif.',
  },
  {
    cle: 'reste_du',
    label: 'Restant Dû TTC',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['restant du', 'reste du', 'solde', 'balance', 'outstanding', 'restant', 'montant restant', 'encours'],
    hint: 'Optionnel. Si vide, prend la valeur du Montant TTC. Utile pour importer un historique partiellement réglé.',
  },
]
