// Définition des champs cibles pour chaque type d'import
// Utilisé par les hooks d'import ET les composants de mapping
import type { ChampCible } from '../types/import'

export const CHAMPS_BANCAIRES: ChampCible[] = [
  {
    cle: 'id_operation',
    label: 'N° Opération (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: false,
    aliases: [
      'n operation', 'no operation', 'numero operation', 'numerodoperation',
      'ref operation', 'reference operation', 'id operation', 'transaction id',
      'reference', 'ref', 'numero',
    ],
  },
  {
    cle: 'date_operation',
    label: 'Date opération',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['date', 'date valeur', 'date operation', 'date ope', 'date transaction', 'valeur date'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'libelle',
    label: 'Libellé',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['libelle', 'intitule', 'description', 'motif', 'objet', 'designation', 'wording'],
  },
  {
    cle: 'detail',
    label: 'Réf. client / Communication',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['detail', 'ref client', 'reference client', 'communication', 'info complementaire'],
  },
  {
    cle: 'infos_complementaires',
    label: 'Informations complémentaires',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['infos complementaires', 'informations complementaires', 'info', 'note', 'remarque', 'observation'],
    hint: 'Visible par l\'opérateur lors du lettrage',
  },
  {
    cle: 'debit',
    label: 'Débit (non-lettrable)',
    est_pivot: false,
    requis: false,
    est_lettrable: false,  // les débits ne sont pas utilisés dans le lettrage
    aliases: ['debit', 'montant debit', 'sortie', 'depense', 'retrait'],
  },
  {
    cle: 'credit',
    label: 'Crédit',
    est_pivot: false,
    requis: false,
    est_lettrable: true,
    aliases: ['credit', 'montant credit', 'entree', 'encaissement', 'versement', 'depot'],
  },
]

export const CHAMPS_LETTRAGES: ChampCible[] = [
  {
    cle: 'numero_facture',
    label: 'N° de facture (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: true,
    aliases: ['numero facture', 'num facture', 'no facture', 'facture', 'piece', 'reference', 'ref', 'numerodepiece', 'n piece'],
  },
  {
    cle: 'montant',
    label: 'Montant lettré',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['montant', 'montant lettre', 'montant paye', 'montant regle', 'amount', 'total', 'reglement'],
    hint: 'Arrondi à 2 décimales',
  },
  {
    cle: 'date_lettrage',
    label: 'Date de lettrage',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['date lettrage', 'date paiement', 'date reglement', 'date', 'payment date', 'date prelevement'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'code_client',
    label: 'Code client',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['code client', 'client', 'code dso', 'dso'],
    hint: 'Déduit automatiquement depuis la facture si absent',
  },
  {
    cle: 'id_ligne_bancaire',
    label: 'N° Opération bancaire',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['id operation', 'ref operation', 'n operation', 'operation', 'virement', 'transaction'],
  },
  {
    cle: 'commentaire',
    label: 'Commentaire',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['commentaire', 'note', 'observation', 'remarque', 'motif'],
  },
]

export const CHAMPS_GROUPEMENTS: ChampCible[] = [
  {
    cle: 'code_client',
    label: 'Code client (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'codedso', 'dso', 'code'],
  },
  {
    cle: 'code_groupement',
    label: 'Code groupement',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['code groupement', 'codegroupement', 'groupement', 'groupe', 'group', 'code groupe'],
    hint: 'Identifiant commun à plusieurs clients du même groupe',
  },
]

export const CHAMPS_CLIENTS: ChampCible[] = [
  {
    cle: 'code_dso',
    label: 'Code client (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'codedso', 'dso', 'code', 'code_client'],
  },
  {
    cle: 'nom',
    label: 'Nom du client',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['nom', 'nom client', 'nomclient', 'raison sociale', 'raisonsociale', 'societe', 'client'],
  },
  {
    cle: 'commercial',
    label: 'Commercial',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['commercial', 'responsable commercial', 'commercial responsable', 'vendeur'],
  },
  {
    cle: 'operateur',
    label: 'Opérateur',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['operateur', 'operateur dso', 'gestionnaire', 'charge de compte'],
  },
  {
    cle: 'plateforme',
    label: "Plateforme d'envoi",
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['plateforme', 'plateforme envoi', 'portail', 'chorus', 'cegedim', 'mode envoi'],
    hint: 'Ex : Chorus, Cegedim, Tungsten…',
  },
  {
    cle: 'code_groupement',
    label: 'Code groupement',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['code groupement', 'codegroupement', 'groupement', 'groupe', 'group', 'code groupe'],
    hint: 'Identifiant commun aux clients d\'un même groupe (vue Nébuleuse)',
  },
]

export const CHAMPS_FACTURES: ChampCible[] = [
  {
    cle: 'numero_piece',
    label: 'N° de pièce (pivot)',
    est_pivot: true,
    requis: true,
    est_lettrable: true,
    aliases: [
      'numero piece', 'num piece', 'no piece', 'numerodepiece',
      'n facture', 'no facture', 'numero facture', 'ref facture',
      'piece', 'reference', 'ref',
    ],
  },
  {
    cle: 'code_client',
    label: 'Code client',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['code client', 'codeclient', 'code dso', 'codedso', 'dso', 'code'],
  },
  {
    cle: 'nom_client',
    label: 'Nom du client',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['nom client', 'nomclient', 'client', 'raison sociale', 'raisonsociale', 'nom', 'societe'],
  },
  {
    cle: 'date_emission',
    label: "Date d'émission",
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['date emission', 'datemission', 'date facture', 'datefacture', 'date creation', 'date'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'date_echeance',
    label: "Date d'échéance",
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['echeance', 'date echeance', 'dateecheance', 'due date', 'duedate', 'expiration'],
    hint: 'Format attendu : jj/mm/aaaa',
  },
  {
    cle: 'montant_ht',
    label: 'Montant HT',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['montant ht', 'montantht', 'total ht', 'totalht', 'ht', 'montant hors taxe'],
    hint: 'Arrondi à 2 décimales',
  },
  {
    cle: 'montant_ttc',
    label: 'Montant TTC',
    est_pivot: false,
    requis: true,
    est_lettrable: false,
    aliases: ['montant ttc', 'montantttc', 'total ttc', 'totalttc', 'montant', 'total', 'ttc', 'amount'],
    hint: 'Arrondi à 2 décimales',
  },
  {
    cle: 'est_avoir',
    label: 'Avoir ?',
    est_pivot: false,
    requis: false,
    est_lettrable: false,
    aliases: ['avoir', 'est avoir', 'estavoir', 'type', 'nature document'],
    hint: 'Valeurs acceptées : AVOIR, OUI, 1, TRUE',
  },
]
